// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// stream_tx //
// --------- //

#define stream_tx_wrap_target 0
#define stream_tx_wrap 6
#define stream_tx_pio_version 0

static const uint16_t stream_tx_program_instructions[] = {
            //     .wrap_target
    0x95a0, //  0: pull   block           side 1 [5] 
    0xf03f, //  1: set    x, 31           side 1     
    0xf05f, //  2: set    y, 31           side 1     
    0x6601, //  3: out    pins, 1         side 0 [6] 
    0x0043, //  4: jmp    x--, 3          side 0     
    0x6601, //  5: out    pins, 1         side 0 [6] 
    0x0085, //  6: jmp    y--, 5          side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program stream_tx_program = {
    .instructions = stream_tx_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config stream_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + stream_tx_wrap_target, offset + stream_tx_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
static inline void stream_tx_program_init(PIO pio, uint sm, uint offset, uint pin_tx, uint pin_frame, uint baud) {
    // Tell PIO to initially drive output-high on the selected pin, then map PIO
    // onto that pin with the IO muxes.
    pio_sm_set_pins_with_mask64(pio, sm, (1ull << pin_tx) | (1ull << pin_frame), 
                                          (1ull << pin_tx) | (1ull << pin_frame));
    pio_sm_set_pindirs_with_mask64(pio, sm, (1ull << pin_tx) | (1ull << pin_frame), 
                                             (1ull << pin_tx) | (1ull << pin_frame));
    pio_gpio_init(pio, pin_tx);
    pio_gpio_init(pio, pin_frame);
    pio_sm_config c = stream_tx_program_get_default_config(offset);
    // OUT shifts to right, autopull enabled
    sm_config_set_out_shift(&c, true, true, 32);
    sm_config_set_out_pins(&c, pin_tx, 1);
    sm_config_set_sideset_pins(&c, pin_frame);
    // We only need TX, so get an 8-deep FIFO!
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    // SM transmits 1 bit per 8 execution cycles.
    float div = (float)clock_get_hz(clk_sys) / (8 * baud);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline void stream_tx_program_putc(PIO pio, uint sm, char c) {
    pio_sm_put_blocking(pio, sm, (uint32_t)c);
}
static inline void stream_tx_program_puts(PIO pio, uint sm, const char *s) {
    while (*s)
        uart_tx_program_putc(pio, sm, *s++);
}

#endif

