// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// stream_rx //
// --------- //

#define stream_rx_wrap_target 0
#define stream_rx_wrap 9
#define stream_rx_pio_version 0

static const uint16_t stream_rx_program_instructions[] = {
            //     .wrap_target
    0x2021, //  0: wait   0 pin, 1                   
    0xe03f, //  1: set    x, 31                      
    0xe15f, //  2: set    y, 31                  [1] 
    0x4001, //  3: in     pins, 1                    
    0x0643, //  4: jmp    x--, 3                 [6] 
    0x4001, //  5: in     pins, 1                    
    0x0685, //  6: jmp    y--, 5                 [6] 
    0x00c0, //  7: jmp    pin, 0                     
    0x20a1, //  8: wait   1 pin, 1                   
    0x0000, //  9: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program stream_rx_program = {
    .instructions = stream_rx_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config stream_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + stream_rx_wrap_target, offset + stream_rx_wrap);
    return c;
}

static inline void stream_rx_program_init(PIO pio, uint sm, uint offset, uint pin, uint baud) {
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    pio_sm_set_consecutive_pindirs(pio, sm, pin+1, 1, false);
    //data pin
    pio_gpio_init(pio, pin);
    gpio_pull_up(pin);
    //frame pin
    pio_gpio_init(pio, pin+1);
    gpio_pull_up(pin+1);
    pio_sm_config c = stream_rx_program_get_default_config(offset);
    sm_config_set_in_pin_base(&c, pin); // for IN
    sm_config_set_in_pin_count(&c, 1);  //data=pin and frame=pin+1
    sm_config_set_jmp_pin(&c, pin+1); // for JMP
    // Shift to right, autopush enabled
    sm_config_set_in_shift(&c, true, true, 32);
    // Deeper FIFO as we're not doing any TX
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    // SM transmits 1 bit per 8 execution cycles.
    float div = (float)clock_get_hz(clk_sys) / (8 * baud);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

