// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// piocx_tx //
// -------- //

#define piocx_tx_wrap_target 0
#define piocx_tx_wrap 5
#define piocx_tx_pio_version 0

static const uint16_t piocx_tx_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0xbf42, //  1: nop                           [31]
    0xbf42, //  2: nop                           [31]
    0xe000, //  3: set    pins, 0                    
    0xbf42, //  4: nop                           [31]
    0xbf42, //  5: nop                           [31]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program piocx_tx_program = {
    .instructions = piocx_tx_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config piocx_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + piocx_tx_wrap_target, offset + piocx_tx_wrap);
    return c;
}

static inline void piocx_tx_program_init(PIO pio, uint sm, uint offset, uint data_pin, uint frame_pin, float clk_div) {
    // Set pins LOW and as outputs BEFORE pio_sm_init (like uart_tx example)
    pio_sm_set_pins_with_mask(pio, sm, 0, (1u << data_pin) | (1u << frame_pin));
    pio_sm_set_pindirs_with_mask(pio, sm, (1u << data_pin) | (1u << frame_pin),
                                  (1u << data_pin) | (1u << frame_pin));
    // Hand pins to PIO control
    pio_gpio_init(pio, data_pin);
    pio_gpio_init(pio, frame_pin);
    // Now build the config
    pio_sm_config c = piocx_tx_program_get_default_config(offset);
    // For this test: SET controls just GPIO 0 (data_pin)
    sm_config_set_set_pins(&c, data_pin, 1);
    sm_config_set_clkdiv(&c, clk_div);
    // Initialize and enable
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

