// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// piocx_rx //
// -------- //

#define piocx_rx_wrap_target 0
#define piocx_rx_wrap 6
#define piocx_rx_pio_version 0

static const uint16_t piocx_rx_program_instructions[] = {
            //     .wrap_target
    0x2085, //  0: wait   1 gpio, 5                  
    0xe026, //  1: set    x, 6                       
    0xe048, //  2: set    y, 8                       
    0x4001, //  3: in     pins, 1                    
    0x0083, //  4: jmp    y--, 3                     
    0x0042, //  5: jmp    x--, 2                     
    0x2005, //  6: wait   0 gpio, 5                  
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program piocx_rx_program = {
    .instructions = piocx_rx_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config piocx_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + piocx_rx_wrap_target, offset + piocx_rx_wrap);
    return c;
}

static inline void piocx_rx_program_init(PIO pio, uint sm, uint offset, uint data_pin, uint frame_pin, float clk_div) {
    // Set pins as inputs BEFORE pio_sm_init
    pio_sm_set_pindirs_with_mask(pio, sm, 0, (1u << data_pin) | (1u << frame_pin));
    // Hand pins to PIO control
    pio_gpio_init(pio, data_pin);
    pio_gpio_init(pio, frame_pin);
    // Build config
    pio_sm_config c = piocx_rx_program_get_default_config(offset);
    sm_config_set_in_shift(&c, true, true, 8);  // LSB first, autopush at 8 bits
    sm_config_set_in_pins(&c, data_pin);
    sm_config_set_clkdiv(&c, clk_div);
    // Initialize and enable
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

