// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// simple_tx //
// --------- //

#define simple_tx_wrap_target 0
#define simple_tx_wrap 3
#define simple_tx_pio_version 0

static const uint16_t simple_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xe027, //  1: set    x, 7                       
    0x6001, //  2: out    pins, 1                    
    0x0042, //  3: jmp    x--, 2                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program simple_tx_program = {
    .instructions = simple_tx_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config simple_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + simple_tx_wrap_target, offset + simple_tx_wrap);
    return c;
}

static inline void simple_tx_program_init(PIO pio, uint sm, uint offset, uint data_pin, float clk_div) {
    pio_sm_config c = simple_tx_program_get_default_config(offset);
    // Configure data pin as OUT
    sm_config_set_out_pins(&c, data_pin, 1);
    pio_gpio_init(pio, data_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, data_pin, 1, true);
    // Shift out LSB first, no autopull
    sm_config_set_out_shift(&c, true, false, 32);
    // Set clock divider
    sm_config_set_clkdiv(&c, clk_div);
    // Initialize and enable
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

