// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// test_set_both //
// ------------- //

#define test_set_both_wrap_target 0
#define test_set_both_wrap 7
#define test_set_both_pio_version 0

static const uint16_t test_set_both_program_instructions[] = {
            //     .wrap_target
    0xe003, //  0: set    pins, 3                    
    0xbf42, //  1: nop                           [31]
    0xe002, //  2: set    pins, 2                    
    0xbf42, //  3: nop                           [31]
    0xe001, //  4: set    pins, 1                    
    0xbf42, //  5: nop                           [31]
    0xe000, //  6: set    pins, 0                    
    0xbf42, //  7: nop                           [31]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program test_set_both_program = {
    .instructions = test_set_both_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config test_set_both_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + test_set_both_wrap_target, offset + test_set_both_wrap);
    return c;
}

static inline void test_set_both_program_init(PIO pio, uint sm, uint offset, uint data_pin, uint frame_pin, float clk_div) {
    pio_sm_config c = test_set_both_program_get_default_config(offset);
    // Set BOTH pins as SET pins (data pin first, then frame pin)
    sm_config_set_set_pins(&c, data_pin, 2);  // 2 consecutive pins starting at data_pin
    sm_config_set_clkdiv(&c, clk_div);
    pio_sm_init(pio, sm, offset, &c);
    pio_gpio_init(pio, data_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, data_pin, 2, true);  // Both as outputs
    pio_sm_set_enabled(pio, sm, true);
}

#endif

